import 'package:flutter/material.dart';

class AppSettings extends ChangeNotifier {
  static final AppSettings _instance = AppSettings._internal();
  factory AppSettings() => _instance;
  AppSettings._internal();

  // ── Theme ──────────────────────────────────────────────────────────────────
  bool _isDarkGreen = false;
  bool get isDarkGreen => _isDarkGreen;
  void setTheme(bool isDarkGreen) {
    _isDarkGreen = isDarkGreen;
    notifyListeners();
  }

  ThemeData get themeData {
    if (_isDarkGreen) {
      return ThemeData(
        brightness: Brightness.dark,
        primaryColor: const Color(0xFF2ECC71),
        scaffoldBackgroundColor: const Color(0xFF061A0C),
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF2ECC71),
          secondary: Color(0xFF1A6B35),
        ),
      );
    } else {
      return ThemeData(
        brightness: Brightness.light,
        primaryColor: const Color(0xFF2ECC71),
        scaffoldBackgroundColor: const Color(0xFFF5FBF7),
        colorScheme: const ColorScheme.light(
          primary: Color(0xFF2ECC71),
          secondary: Color(0xFF1A6B35),
        ),
      );
    }
  }

  // ── Theme Colors ──────────────────────────────────────────────────────────
  Color get bgColor => _isDarkGreen ? const Color(0xFF061A0C) : const Color(0xFFF5FBF7);
  Color get cardColor => _isDarkGreen ? const Color(0xFF0D2B15) : const Color(0xFFFFFFFF);
  Color get cardAltColor => _isDarkGreen ? const Color(0xFF163D22) : const Color(0xFFE8F8EF);
  Color get textDark => _isDarkGreen ? const Color(0xFFECF9F1) : const Color(0xFF1A2E22);
  Color get textGrey => _isDarkGreen ? const Color(0xFF7AB08A) : const Color(0xFF7A9B85);
  Color get dividerColor => _isDarkGreen ? const Color(0xFF1A4D2E) : const Color(0xFFDDEEE4);
  Color get inputFillColor => _isDarkGreen ? const Color(0xFF112A17) : const Color(0xFFE8F8EF);
  Color get inputTextColor => _isDarkGreen ? const Color(0xFFECF9F1) : const Color(0xFF1A2E22);
  Color get buttonTextColor => Colors.white;
  Color get buttonBorderColor => _isDarkGreen ? const Color(0xFF2ECC71).withOpacity(0.5) : const Color(0xFF2ECC71);
  Color get buttonBgColor => _isDarkGreen ? const Color(0xFF1A6B35) : const Color(0xFF2ECC71);
  Color get sectionTitleColor => _isDarkGreen ? const Color(0xFFECF9F1) : const Color(0xFF1A2E22);
  
  static const Color kGreen = Color(0xFF2ECC71);
  static const Color kDanger = Color(0xFFFF5252);
  static const Color kWarning = Color(0xFFFFB300);
  static const Color kBlue = Color(0xFF29B6F6);

  // ── Language ───────────────────────────────────────────────────────────────
  String _languageCode = 'en';
  String get languageCode => _languageCode;
  Locale get locale => Locale(_languageCode);
  void setLanguage(String code) {
    _languageCode = code;
    notifyListeners();
  }

  // ── Temperature ────────────────────────────────────────────────────────────
  String _tempUnit = 'celsius';
  String get tempUnit => _tempUnit;
  void setTempUnit(String unit) {
    _tempUnit = unit;
    notifyListeners();
  }

  String convertTemp(double celsius) {
    switch (_tempUnit) {
      case 'fahrenheit': return '${((celsius * 9 / 5) + 32).round()}°F';
      case 'kelvin': return '${(celsius + 273.15).round()}K';
      default: return '${celsius.round()}°C';
    }
  }

  static const Map<String, String> tempUnits = {
    'celsius': 'Celsius (°C)',
    'fahrenheit': 'Fahrenheit (°F)',
    'kelvin': 'Kelvin (K)',
  };

  static const Map<String, String> languages = {
    'en': '🇬🇧  English',
    'hi': '🇮🇳  हिंदी (Hindi)',
    'fr': '🇫🇷  Français (French)',
    'de': '🇩🇪  Deutsch (German)',
    'zh': '🇨🇳  中文 (Chinese)',
    'ja': '🇯🇵  日本語 (Japanese)',
  };

  // ── Translations ───────────────────────────────────────────────────────────
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Smart Farmer',
      'save': 'Save Changes',
      'cancel': 'Cancel',
      'not_set': 'Not set',
      'version': 'Smart Farmer v1.0.0',
      'coming_soon': 'Coming Soon!',
      'building': 'We are building this for you',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'welcome_back': 'Welcome Back',
      'email': 'Email',
      'password': 'Password',
      'sign_in': 'Sign in',
      'sign_up': 'Sign Up',
      'forgot_password': 'Forgot Password',
      'register_phone': 'Register with Phone Number',
      'login_failed': 'Login failed',
      'fill_all_fields': 'Please fill all fields!',
      'create_account': 'Create\nAccount',
      'name': 'Name',
      'phone': 'Phone',
      'confirm_password': 'Confirm-Password',
      'register': 'Register',
      'passwords_no_match': 'Passwords do not match',
      'account_created': 'Account created successfully!',
      'registration_failed': 'Registration failed',
      'weather': 'Weather',
      'hourly_forecast': 'Hourly Forecast',
      'weekly_forecast': 'Weekly Forecast',
      'now': 'Now',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'feels_like': 'Feels Like',
      'search_city': 'Search city...',
      'gps_coming': 'GPS coming soon!',
      'ai_tip': 'AI Farming Tip',
      'tip_rain': 'Skip irrigation — rain will water crops!',
      'tip_storm': 'Protect crops! Strong winds incoming.',
      'tip_clear': 'Check soil moisture and water if needed.',
      'tip_clouds': 'Good day for farming activities!',
      'tip_frost': 'Frost alert! Cover sensitive crops.',
      'tip_default': 'Check crop conditions today.',
      'pick_location': 'Pick Location',
      'find_city': 'Find your city for weather info',
      'soil': 'Soil',
      'soil_monitor': 'Soil Monitor',
      'soil_health': 'Soil Health',
      'soil_health_good': 'Good',
      'soil_health_fair': 'Fair',
      'soil_health_poor': 'Poor',
      'moisture': 'Moisture',
      'temperature': 'Temperature Unit',
      'ph_level': 'pH Level',
      'nitrogen': 'Nitrogen (N)',
      'phosphorus': 'Phosphorus (P)',
      'potassium': 'Potassium (K)',
      'last_updated': 'Last updated',
      'optimal': 'Optimal',
      'low': 'Low',
      'high': 'High',
      'connect_sensor': 'Connect IoT Sensor',
      'sensor_tip': 'Connect your sensor to get real-time soil data',
      'npk_nutrients': 'NPK Nutrients',
      'soil_conditions': 'Soil Conditions',
      'recommendations': 'Recommendations',
      'alerts': 'Alerts',
      'all_normal': 'All conditions normal',
      'critical': 'Critical',
      'warning': 'Warning',
      'info': 'Info',
      'all': 'All',
      'no_alerts': 'No alerts in this category',
      'total': 'Total',
      'warnings': 'Warnings',
      'soil_dry': 'Critical: Soil Too Dry',
      'soil_wet': 'Soil Overwatered',
      'high_temp': 'High Soil Temperature',
      'low_temp': 'Low Soil Temperature',
      'too_acidic': 'Soil Too Acidic',
      'too_alkaline': 'Soil Too Alkaline',
      'low_nitrogen': 'Low Nitrogen (N)',
      'low_phosphorus': 'Low Phosphorus (P)',
      'low_potassium': 'Low Potassium (K)',
      'disease_risk': 'Disease Risk: Fungal Infection',
      'sensor_active': 'IoT Sensor Active',
      'all_conditions_normal': 'All Soil Conditions Normal',
      'ai_chat': 'Smart Farming AI',
      'ai_subtitle': 'Ask me about your crops!',
      'ai_hello': 'Hello Farmer! I am your Smart Farming AI. Ask me anything about your crops, soil, or weather!',
      'ai_input': 'Ask about crops, soil, weather...',
      'profile': 'Profile',
      'smart_farmer': 'Smart Farmer',
      'personal_info': 'Personal Information',
      'full_name': 'Full Name',
      'edit_profile': 'Edit Profile',
      'farm_details': 'My Farm Details',
      'location': 'Location',
      'crop_type': 'Crop Type',
      'farm_size': 'Farm Size',
      'irrigation': 'Irrigation',
      'edit_farm': 'Edit Farm Details',
      'notifications': 'Notifications',
      'enable_notif': 'Enable Notifications',
      'weather_alerts': 'Weather Alerts',
      'soil_alerts': 'Soil Moisture Alerts',
      'app_settings': 'App Settings',
      'language': 'Language',
      'temp_unit': 'Temperature Unit',
      'theme': 'Theme',
      'legal': 'Legal',
      'terms': 'Terms & Conditions',
      'privacy': 'Privacy Policy',
      'about': 'About App',
      'rate': 'Rate App',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'dark_green': 'Dark Green',
      'light': 'Light',
      'celsius': 'Celsius (°C)',
      'fahrenheit': 'Fahrenheit (°F)',
      'kelvin': 'Kelvin (K)',
      'nav_weather': 'Weather',
      'nav_soil': 'Soil',
      'nav_alerts': 'Alerts',
      'nav_profile': 'Profile',
    },
    'hi': {
      'app_name': 'स्मार्ट किसान',
      'save': 'परिवर्तन सहेजें',
      'cancel': 'रद्द करें',
      'not_set': 'सेट नहीं',
      'version': 'स्मार्ट फार्मर v1.0.0',
      'coming_soon': 'जल्द आ रहा है!',
      'building': 'हम आपके लिए इसे बना रहे हैं',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'retry': 'पुनः प्रयास',
      'welcome_back': 'वापसी पर स्वागत',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'sign_in': 'साइन इन',
      'sign_up': 'साइन अप',
      'forgot_password': 'पासवर्ड भूल गए',
      'register_phone': 'फोन नंबर से पंजीकरण',
      'login_failed': 'लॉगिन विफल',
      'fill_all_fields': 'कृपया सभी फ़ील्ड भरें!',
      'create_account': 'खाता\nबनाएं',
      'name': 'नाम',
      'phone': 'फोन',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'register': 'पंजीकरण',
      'passwords_no_match': 'पासवर्ड मेल नहीं खाते',
      'account_created': 'खाता सफलतापूर्वक बनाया गया!',
      'registration_failed': 'पंजीकरण विफल',
      'weather': 'मौसम',
      'hourly_forecast': 'प्रति घंटा पूर्वानुमान',
      'weekly_forecast': 'साप्ताहिक पूर्वानुमान',
      'now': 'अभी',
      'humidity': 'नमी',
      'wind': 'हवा',
      'feels_like': 'महसूस होता है',
      'search_city': 'शहर खोजें...',
      'gps_coming': 'GPS जल्द आ रहा है!',
      'ai_tip': 'AI खेती टिप',
      'tip_rain': 'सिंचाई छोड़ें — बारिश फसल को पानी देगी!',
      'tip_storm': 'फसल की रक्षा करें! तेज़ हवाएं आ रही हैं।',
      'tip_clear': 'मिट्टी की नमी जांचें और जरूरत पड़ने पर पानी दें।',
      'tip_clouds': 'खेती के लिए अच्छा दिन!',
      'tip_frost': 'पाला चेतावनी! संवेदनशील फसलों को ढकें।',
      'tip_default': 'आज फसल की स्थिति जांचें।',
      'pick_location': 'स्थान चुनें',
      'find_city': 'मौसम की जानकारी के लिए अपना शहर खोजें',
      'soil': 'मिट्टी',
      'soil_monitor': 'मिट्टी मॉनिटर',
      'soil_health': 'मिट्टी का स्वास्थ्य',
      'soil_health_good': 'अच्छा',
      'soil_health_fair': 'ठीक',
      'soil_health_poor': 'खराब',
      'moisture': 'नमी',
      'temperature': 'तापमान',
      'ph_level': 'pH स्तर',
      'nitrogen': 'नाइट्रोजन (N)',
      'phosphorus': 'फास्फोरस (P)',
      'potassium': 'पोटेशियम (K)',
      'last_updated': 'अंतिम अपडेट',
      'optimal': 'सर्वोत्तम',
      'low': 'कम',
      'high': 'अधिक',
      'connect_sensor': 'IoT सेंसर कनेक्ट करें',
      'sensor_tip': 'रियल-टाइम मिट्टी डेटा के लिए सेंसर कनेक्ट करें',
      'npk_nutrients': 'NPK पोषक तत्व',
      'soil_conditions': 'मिट्टी की स्थिति',
      'recommendations': 'सिफारिशें',
      'alerts': 'अलर्ट',
      'all_normal': 'सभी स्थितियां सामान्य',
      'critical': 'गंभीर',
      'warning': 'चेतावनी',
      'info': 'जानकारी',
      'all': 'सभी',
      'no_alerts': 'इस श्रेणी में कोई अलर्ट नहीं',
      'total': 'कुल',
      'warnings': 'चेतावनियां',
      'ai_chat': 'स्मार्ट खेती AI',
      'ai_subtitle': 'अपनी फसलों के बारे में पूछें!',
      'ai_hello': 'नमस्ते किसान! मैं आपका स्मार्ट खेती AI हूं। फसलों, मिट्टी या मौसम के बारे में कुछ भी पूछें!',
      'ai_input': 'फसल, मिट्टी, मौसम के बारे में पूछें...',
      'profile': 'प्रोफाइल',
      'smart_farmer': 'स्मार्ट किसान',
      'personal_info': 'व्यक्तिगत जानकारी',
      'full_name': 'पूरा नाम',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'farm_details': 'मेरी खेत की जानकारी',
      'location': 'स्थान',
      'crop_type': 'फसल का प्रकार',
      'farm_size': 'खेत का आकार',
      'irrigation': 'सिंचाई',
      'edit_farm': 'खेत की जानकारी संपादित करें',
      'notifications': 'सूचनाएं',
      'enable_notif': 'सूचनाएं सक्षम करें',
      'weather_alerts': 'मौसम अलर्ट',
      'soil_alerts': 'मिट्टी नमी अलर्ट',
      'app_settings': 'ऐप सेटिंग्स',
      'language': 'भाषा',
      'temp_unit': 'तापमान इकाई',
      'theme': 'थीम',
      'legal': 'कानूनी',
      'terms': 'नियम और शर्तें',
      'privacy': 'गोपनीयता नीति',
      'about': 'ऐप के बारे में',
      'rate': 'ऐप रेट करें',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      'dark_green': 'गहरा हरा',
      'light': 'हल्का',
      'celsius': 'सेल्सियस (°C)',
      'fahrenheit': 'फ़ारेनहाइट (°F)',
      'kelvin': 'केल्विन (K)',
      'nav_weather': 'मौसम',
      'nav_soil': 'मिट्टी',
      'nav_alerts': 'अलर्ट',
      'nav_profile': 'प्रोफाइल',
      'soil_dry': 'गंभीर: मिट्टी बहुत सूखी',
      'soil_wet': 'मिट्टी में अधिक पानी',
      'high_temp': 'मिट्टी का तापमान अधिक',
      'low_temp': 'मिट्टी का तापमान कम',
      'too_acidic': 'मिट्टी बहुत अम्लीय',
      'too_alkaline': 'मिट्टी बहुत क्षारीय',
      'low_nitrogen': 'कम नाइट्रोजन (N)',
      'low_phosphorus': 'कम फास्फोरस (P)',
      'low_potassium': 'कम पोटेशियम (K)',
      'disease_risk': 'रोग जोखिम: फंगल संक्रमण',
      'sensor_active': 'IoT सेंसर सक्रिय',
      'all_conditions_normal': 'सभी मिट्टी स्थितियां सामान्य',
    },
    'fr': {
      'app_name': 'Agriculteur Intelligent',
      'save': 'Sauvegarder',
      'cancel': 'Annuler',
      'not_set': 'Non défini',
      'version': 'Smart Farmer v1.0.0',
      'coming_soon': 'Bientôt disponible!',
      'building': 'Nous construisons cela pour vous',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'retry': 'Réessayer',
      'welcome_back': 'Bienvenue',
      'email': 'Email',
      'password': 'Mot de passe',
      'sign_in': 'Se connecter',
      'sign_up': 'S\'inscrire',
      'forgot_password': 'Mot de passe oublié',
      'register_phone': 'S\'inscrire avec numéro de téléphone',
      'login_failed': 'Connexion échouée',
      'fill_all_fields': 'Veuillez remplir tous les champs!',
      'create_account': 'Créer\nun compte',
      'name': 'Nom',
      'phone': 'Téléphone',
      'confirm_password': 'Confirmer le mot de passe',
      'register': 'S\'inscrire',
      'passwords_no_match': 'Les mots de passe ne correspondent pas',
      'account_created': 'Compte créé avec succès!',
      'registration_failed': 'Inscription échouée',
      'weather': 'Météo',
      'hourly_forecast': 'Prévisions horaires',
      'weekly_forecast': 'Prévisions hebdomadaires',
      'now': 'Maintenant',
      'humidity': 'Humidité',
      'wind': 'Vent',
      'feels_like': 'Ressenti',
      'search_city': 'Rechercher une ville...',
      'gps_coming': 'GPS bientôt disponible!',
      'ai_tip': 'Conseil agricole IA',
      'tip_rain': 'Pas d\'irrigation — la pluie arrosera les cultures!',
      'tip_storm': 'Protégez les cultures! Vents forts à venir.',
      'tip_clear': 'Vérifiez l\'humidité du sol et arrosez si nécessaire.',
      'tip_clouds': 'Bonne journée pour les activités agricoles!',
      'tip_frost': 'Alerte gel! Couvrez les cultures sensibles.',
      'tip_default': 'Vérifiez l\'état des cultures aujourd\'hui.',
      'pick_location': 'Choisir un lieu',
      'find_city': 'Trouvez votre ville pour les infos météo',
      'soil': 'Sol',
      'soil_monitor': 'Moniteur de sol',
      'soil_health': 'Santé du sol',
      'soil_health_good': 'Bon',
      'soil_health_fair': 'Correct',
      'soil_health_poor': 'Mauvais',
      'moisture': 'Humidité',
      'temperature': 'Température',
      'ph_level': 'Niveau pH',
      'nitrogen': 'Azote (N)',
      'phosphorus': 'Phosphore (P)',
      'potassium': 'Potassium (K)',
      'last_updated': 'Dernière mise à jour',
      'optimal': 'Optimal',
      'low': 'Faible',
      'high': 'Élevé',
      'connect_sensor': 'Connecter le capteur IoT',
      'sensor_tip': 'Connectez votre capteur pour des données en temps réel',
      'npk_nutrients': 'Nutriments NPK',
      'soil_conditions': 'Conditions du sol',
      'recommendations': 'Recommandations',
      'alerts': 'Alertes',
      'all_normal': 'Toutes les conditions sont normales',
      'critical': 'Critique',
      'warning': 'Avertissement',
      'info': 'Info',
      'all': 'Tout',
      'no_alerts': 'Aucune alerte dans cette catégorie',
      'total': 'Total',
      'warnings': 'Avertissements',
      'ai_chat': 'IA Agricole Intelligente',
      'ai_subtitle': 'Demandez-moi sur vos cultures!',
      'ai_hello': 'Bonjour Agriculteur! Je suis votre IA agricole. Posez-moi des questions sur vos cultures, le sol ou la météo!',
      'ai_input': 'Demandez sur les cultures, le sol, la météo...',
      'profile': 'Profil',
      'smart_farmer': 'Agriculteur Intelligent',
      'personal_info': 'Informations personnelles',
      'full_name': 'Nom complet',
      'edit_profile': 'Modifier le profil',
      'farm_details': 'Détails de ma ferme',
      'location': 'Emplacement',
      'crop_type': 'Type de culture',
      'farm_size': 'Taille de la ferme',
      'irrigation': 'Irrigation',
      'edit_farm': 'Modifier les détails',
      'notifications': 'Notifications',
      'enable_notif': 'Activer les notifications',
      'weather_alerts': 'Alertes météo',
      'soil_alerts': 'Alertes humidité du sol',
      'app_settings': 'Paramètres',
      'language': 'Langue',
      'temp_unit': 'Unité de température',
      'theme': 'Thème',
      'legal': 'Légal',
      'terms': 'Conditions d\'utilisation',
      'privacy': 'Politique de confidentialité',
      'about': 'À propos',
      'rate': 'Noter l\'application',
      'logout': 'Déconnexion',
      'logout_confirm': 'Voulez-vous vous déconnecter?',
      'dark_green': 'Vert foncé',
      'light': 'Clair',
      'celsius': 'Celsius (°C)',
      'fahrenheit': 'Fahrenheit (°F)',
      'kelvin': 'Kelvin (K)',
      'nav_weather': 'Météo',
      'nav_soil': 'Sol',
      'nav_alerts': 'Alertes',
      'nav_profile': 'Profil',
      'soil_dry': 'Critique: Sol trop sec',
      'soil_wet': 'Sol trop humide',
      'high_temp': 'Température du sol élevée',
      'low_temp': 'Température du sol basse',
      'too_acidic': 'Sol trop acide',
      'too_alkaline': 'Sol trop alcalin',
      'low_nitrogen': 'Azote faible (N)',
      'low_phosphorus': 'Phosphore faible (P)',
      'low_potassium': 'Potassium faible (K)',
      'disease_risk': 'Risque maladie: Infection fongique',
      'sensor_active': 'Capteur IoT actif',
      'all_conditions_normal': 'Toutes les conditions du sol sont normales',
    },
    'de': {
      'app_name': 'Intelligenter Bauer',
      'save': 'Änderungen speichern',
      'cancel': 'Abbrechen',
      'not_set': 'Nicht eingestellt',
      'version': 'Smart Farmer v1.0.0',
      'coming_soon': 'Demnächst!',
      'building': 'Wir bauen das für Sie',
      'loading': 'Lädt...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'retry': 'Wiederholen',
      'welcome_back': 'Willkommen zurück',
      'email': 'E-Mail',
      'password': 'Passwort',
      'sign_in': 'Anmelden',
      'sign_up': 'Registrieren',
      'forgot_password': 'Passwort vergessen',
      'register_phone': 'Mit Telefonnummer registrieren',
      'login_failed': 'Anmeldung fehlgeschlagen',
      'fill_all_fields': 'Bitte alle Felder ausfüllen!',
      'create_account': 'Konto\nerstellen',
      'name': 'Name',
      'phone': 'Telefon',
      'confirm_password': 'Passwort bestätigen',
      'register': 'Registrieren',
      'passwords_no_match': 'Passwörter stimmen nicht überein',
      'account_created': 'Konto erfolgreich erstellt!',
      'registration_failed': 'Registrierung fehlgeschlagen',
      'weather': 'Wetter',
      'hourly_forecast': 'Stündliche Vorhersage',
      'weekly_forecast': 'Wöchentliche Vorhersage',
      'now': 'Jetzt',
      'humidity': 'Luftfeuchtigkeit',
      'wind': 'Wind',
      'feels_like': 'Gefühlt wie',
      'search_city': 'Stadt suchen...',
      'gps_coming': 'GPS bald verfügbar!',
      'ai_tip': 'KI Landwirtschaftstipp',
      'tip_rain': 'Bewässerung überspringen — Regen bewässert die Ernte!',
      'tip_storm': 'Ernte schützen! Starke Winde kommen.',
      'tip_clear': 'Bodenfeuchtigkeit prüfen und bei Bedarf bewässern.',
      'tip_clouds': 'Guter Tag für landwirtschaftliche Aktivitäten!',
      'tip_frost': 'Frostwarnung! Empfindliche Pflanzen abdecken.',
      'tip_default': 'Heute Erntezustand prüfen.',
      'pick_location': 'Standort wählen',
      'find_city': 'Ihre Stadt für Wetterinformationen finden',
      'soil': 'Boden',
      'soil_monitor': 'Bodenmonitor',
      'soil_health': 'Bodengesundheit',
      'soil_health_good': 'Gut',
      'soil_health_fair': 'Mittelmäßig',
      'soil_health_poor': 'Schlecht',
      'moisture': 'Feuchtigkeit',
      'temperature': 'Temperatur',
      'ph_level': 'pH-Wert',
      'nitrogen': 'Stickstoff (N)',
      'phosphorus': 'Phosphor (P)',
      'potassium': 'Kalium (K)',
      'last_updated': 'Zuletzt aktualisiert',
      'optimal': 'Optimal',
      'low': 'Niedrig',
      'high': 'Hoch',
      'connect_sensor': 'IoT-Sensor verbinden',
      'sensor_tip': 'Sensor verbinden für Echtzeit-Bodendaten',
      'npk_nutrients': 'NPK-Nährstoffe',
      'soil_conditions': 'Bodenbedingungen',
      'recommendations': 'Empfehlungen',
      'alerts': 'Warnungen',
      'all_normal': 'Alle Bedingungen normal',
      'critical': 'Kritisch',
      'warning': 'Warnung',
      'info': 'Info',
      'all': 'Alle',
      'no_alerts': 'Keine Warnungen in dieser Kategorie',
      'total': 'Gesamt',
      'warnings': 'Warnungen',
      'ai_chat': 'Intelligente Landwirtschafts-KI',
      'ai_subtitle': 'Fragen Sie mich über Ihre Ernte!',
      'ai_hello': 'Hallo Bauer! Ich bin Ihre intelligente Landwirtschafts-KI. Stellen Sie mir Fragen zu Ihren Ernten, Boden oder Wetter!',
      'ai_input': 'Fragen Sie über Ernte, Boden, Wetter...',
      'profile': 'Profil',
      'smart_farmer': 'Intelligenter Bauer',
      'personal_info': 'Persönliche Informationen',
      'full_name': 'Vollständiger Name',
      'edit_profile': 'Profil bearbeiten',
      'farm_details': 'Meine Hofdetails',
      'location': 'Standort',
      'crop_type': 'Ernteart',
      'farm_size': 'Hofgröße',
      'irrigation': 'Bewässerung',
      'edit_farm': 'Hofdetails bearbeiten',
      'notifications': 'Benachrichtigungen',
      'enable_notif': 'Benachrichtigungen aktivieren',
      'weather_alerts': 'Wetterwarnungen',
      'soil_alerts': 'Bodenfeuchtigkeit Alarm',
      'app_settings': 'App-Einstellungen',
      'language': 'Sprache',
      'temp_unit': 'Temperatureinheit',
      'theme': 'Thema',
      'legal': 'Rechtliches',
      'terms': 'Nutzungsbedingungen',
      'privacy': 'Datenschutzrichtlinie',
      'about': 'Über die App',
      'rate': 'App bewerten',
      'logout': 'Abmelden',
      'logout_confirm': 'Möchten Sie sich abmelden?',
      'dark_green': 'Dunkelgrün',
      'light': 'Hell',
      'celsius': 'Celsius (°C)',
      'fahrenheit': 'Fahrenheit (°F)',
      'kelvin': 'Kelvin (K)',
      'nav_weather': 'Wetter',
      'nav_soil': 'Boden',
      'nav_alerts': 'Warnungen',
      'nav_profile': 'Profil',
      'soil_dry': 'Kritisch: Boden zu trocken',
      'soil_wet': 'Boden überwässert',
      'high_temp': 'Bodentemperatur zu hoch',
      'low_temp': 'Bodentemperatur zu niedrig',
      'too_acidic': 'Boden zu sauer',
      'too_alkaline': 'Boden zu alkalisch',
      'low_nitrogen': 'Niedriger Stickstoff (N)',
      'low_phosphorus': 'Niedriger Phosphor (P)',
      'low_potassium': 'Niedriges Kalium (K)',
      'disease_risk': 'Krankheitsrisiko: Pilzinfektion',
      'sensor_active': 'IoT-Sensor aktiv',
      'all_conditions_normal': 'Alle Bodenbedingungen normal',
    },
    'zh': {
      'app_name': '智能农民',
      'save': '保存更改',
      'cancel': '取消',
      'not_set': '未设置',
      'version': 'Smart Farmer v1.0.0',
      'coming_soon': '即将推出!',
      'building': '我们正在为您构建',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'retry': '重试',
      'welcome_back': '欢迎回来',
      'email': '邮箱',
      'password': '密码',
      'sign_in': '登录',
      'sign_up': '注册',
      'forgot_password': '忘记密码',
      'register_phone': '用手机号注册',
      'login_failed': '登录失败',
      'fill_all_fields': '请填写所有字段！',
      'create_account': '创建\n账户',
      'name': '姓名',
      'phone': '电话',
      'confirm_password': '确认密码',
      'register': '注册',
      'passwords_no_match': '密码不匹配',
      'account_created': '账户创建成功！',
      'registration_failed': '注册失败',
      'weather': '天气',
      'hourly_forecast': '每小时预报',
      'weekly_forecast': '每周预报',
      'now': '现在',
      'humidity': '湿度',
      'wind': '风',
      'feels_like': '体感温度',
      'search_city': '搜索城市...',
      'gps_coming': 'GPS即将推出！',
      'ai_tip': 'AI农业建议',
      'tip_rain': '跳过灌溉——雨水会浇灌庄稼！',
      'tip_storm': '保护庄稼！强风即将来袭。',
      'tip_clear': '检查土壤湿度，必要时浇水。',
      'tip_clouds': '适合农业活动的好天气！',
      'tip_frost': '霜冻警报！覆盖敏感作物。',
      'tip_default': '今天检查作物状况。',
      'pick_location': '选择位置',
      'find_city': '找到您的城市获取天气信息',
      'soil': '土壤',
      'soil_monitor': '土壤监测',
      'soil_health': '土壤健康',
      'soil_health_good': '良好',
      'soil_health_fair': '一般',
      'soil_health_poor': '差',
      'moisture': '湿度',
      'temperature': '温度',
      'ph_level': 'pH值',
      'nitrogen': '氮 (N)',
      'phosphorus': '磷 (P)',
      'potassium': '钾 (K)',
      'last_updated': '最后更新',
      'optimal': '最佳',
      'low': '低',
      'high': '高',
      'connect_sensor': '连接IoT传感器',
      'sensor_tip': '连接传感器获取实时土壤数据',
      'npk_nutrients': 'NPK营养素',
      'soil_conditions': '土壤条件',
      'recommendations': '建议',
      'alerts': '警报',
      'all_normal': '所有条件正常',
      'critical': '严重',
      'warning': '警告',
      'info': '信息',
      'all': '全部',
      'no_alerts': '此类别无警报',
      'total': '总计',
      'warnings': '警告',
      'ai_chat': '智能农业AI',
      'ai_subtitle': '询问我关于您的作物！',
      'ai_hello': '你好农民！我是您的智能农业AI。问我任何关于作物、土壤或天气的问题！',
      'ai_input': '询问作物、土壤、天气...',
      'profile': '个人资料',
      'smart_farmer': '智能农民',
      'personal_info': '个人信息',
      'full_name': '全名',
      'edit_profile': '编辑资料',
      'farm_details': '我的农场详情',
      'location': '位置',
      'crop_type': '作物类型',
      'farm_size': '农场大小',
      'irrigation': '灌溉',
      'edit_farm': '编辑农场详情',
      'notifications': '通知',
      'enable_notif': '启用通知',
      'weather_alerts': '天气警报',
      'soil_alerts': '土壤湿度警报',
      'app_settings': '应用设置',
      'language': '语言',
      'temp_unit': '温度单位',
      'theme': '主题',
      'legal': '法律',
      'privacy': '隐私政策',
      'about': '关于应用',
      'rate': '评价应用',
      'logout': '退出登录',
      'logout_confirm': '您确定要退出吗？',
      'dark_green': '深绿色',
      'light': '浅色',
      'celsius': '摄氏度 (°C)',
      'fahrenheit': '华氏度 (°F)',
      'kelvin': '开尔文 (K)',
      'nav_weather': '天气',
      'nav_soil': '土壤',
      'nav_alerts': '警报',
      'nav_profile': '个人资料',
      'soil_dry': '严重: 土壤过干',
      'soil_wet': '土壤过湿',
      'high_temp': '土壤温度过高',
      'low_temp': '土壤温度过低',
      'too_acidic': '土壤过酸',
      'too_alkaline': '土壤过碱',
      'low_nitrogen': '氮含量低 (N)',
      'low_phosphorus': '磷含量低 (P)',
      'low_potassium': '钾含量低 (K)',
      'disease_risk': '病害风险: 真菌感染',
      'sensor_active': 'IoT传感器活跃',
      'all_conditions_normal': '所有土壤条件正常',
      'terms': '服务条款',
    },
    'ja': {
      'app_name': 'スマートファーマー',
      'save': '変更を保存',
      'cancel': 'キャンセル',
      'not_set': '未設定',
      'version': 'Smart Farmer v1.0.0',
      'coming_soon': '近日公開！',
      'building': 'あなたのために構築中です',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'retry': '再試行',
      'welcome_back': 'おかえりなさい',
      'email': 'メール',
      'password': 'パスワード',
      'sign_in': 'サインイン',
      'sign_up': 'サインアップ',
      'forgot_password': 'パスワードをお忘れですか',
      'register_phone': '電話番号で登録',
      'login_failed': 'ログイン失敗',
      'fill_all_fields': '全ての項目を入力してください！',
      'create_account': 'アカウント\n作成',
      'name': '名前',
      'phone': '電話',
      'confirm_password': 'パスワードの確認',
      'register': '登録',
      'passwords_no_match': 'パスワードが一致しません',
      'account_created': 'アカウントが作成されました！',
      'registration_failed': '登録に失敗しました',
      'weather': '天気',
      'hourly_forecast': '時間別予報',
      'weekly_forecast': '週間予報',
      'now': '今',
      'humidity': '湿度',
      'wind': '風',
      'feels_like': '体感温度',
      'search_city': '都市を検索...',
      'gps_coming': 'GPS近日公開！',
      'ai_tip': 'AI農業アドバイス',
      'tip_rain': '灌漑不要 — 雨が作物に水を与えます！',
      'tip_storm': '作物を守ってください！強風が来ています。',
      'tip_clear': '土壌水分を確認し、必要なら水やりを。',
      'tip_clouds': '農作業に良い日です！',
      'tip_frost': '霜注意！デリケートな作物を覆ってください。',
      'tip_default': '今日の作物の状態を確認してください。',
      'pick_location': '場所を選択',
      'find_city': '天気情報の都市を検索',
      'soil': '土壌',
      'soil_monitor': '土壌モニター',
      'soil_health': '土壌の健康',
      'soil_health_good': '良好',
      'soil_health_fair': '普通',
      'soil_health_poor': '不良',
      'moisture': '水分',
      'temperature': '温度単位',
      'ph_level': 'pHレベル',
      'nitrogen': '窒素 (N)',
      'phosphorus': 'リン (P)',
      'potassium': 'カリウム (K)',
      'last_updated': '最終更新',
      'optimal': '最適',
      'low': '低',
      'high': '高',
      'connect_sensor': 'IoTセンサーを接続',
      'sensor_tip': 'リアルタイム土壌データのためセンサーを接続',
      'npk_nutrients': 'NPK栄養素',
      'soil_conditions': '土壌状態',
      'recommendations': '推奨事項',
      'alerts': 'アラート',
      'all_normal': 'すべての状態は正常です',
      'critical': '重大',
      'warning': '警告',
      'info': '情報',
      'all': 'すべて',
      'no_alerts': 'このカテゴリにアラートはありません',
      'total': '合計',
      'warnings': '警告',
      'soil_dry': '重大: 土壌が乾燥しすぎ',
      'soil_wet': '土壌過水',
      'high_temp': '土壌温度が高い',
      'low_temp': '土壌温度が低い',
      'too_acidic': '土壌が酸性すぎ',
      'too_alkaline': '土壌がアルカリ性すぎ',
      'low_nitrogen': '窒素不足 (N)',
      'low_phosphorus': 'リン不足 (P)',
      'low_potassium': 'カリウム不足 (K)',
      'disease_risk': '病害リスク: カビ感染',
      'sensor_active': 'IoTセンサー稼働中',
      'all_conditions_normal': '土壌状態はすべて正常',
      'ai_chat': 'スマート農業AI',
      'ai_subtitle': '作物について聞いてください！',
      'ai_hello': 'こんにちは農家さん！私はあなたのスマート農業AIです。作物、土壌、天気について何でも聞いてください！',
      'ai_input': '作物・土壌・天気について質問...',
      'profile': 'プロフィール',
      'smart_farmer': 'スマートファーマー',
      'personal_info': '個人情報',
      'full_name': 'フルネーム',
      'edit_profile': 'プロフィール編集',
      'farm_details': '農場の詳細',
      'location': '場所',
      'crop_type': '作物の種類',
      'farm_size': '農場の大きさ',
      'irrigation': '灌漑',
      'edit_farm': '農場詳細を編集',
      'notifications': '通知',
      'enable_notif': '通知を有効にする',
      'weather_alerts': '天気アラート',
      'soil_alerts': '土壌湿度アラート',
      'app_settings': 'アプリ設定',
      'language': '言語',
      'temp_unit': '温度単位',
      'theme': 'テーマ',
      'legal': '法的事項',
      'terms': '利用規約',
      'privacy': 'プライバシーポリシー',
      'about': 'アプリについて',
      'rate': 'アプリを評価',
      'logout': 'ログアウト',
      'logout_confirm': 'ログアウトしますか？',
      'dark_green': 'ダークグリーン',
      'light': 'ライト',
      'celsius': '摂氏 (°C)',
      'fahrenheit': '華氏 (°F)',
      'kelvin': 'ケルビン (K)',
      'nav_weather': '天気',
      'nav_soil': '土壌',
      'nav_alerts': 'アラート',
      'nav_profile': 'プロフィール',
    },
  };

  // ── t() translation method ─────────────────────────────────────────────────
  String t(String key) {
    return _translations[_languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  // ── Missing color getters ──────────────────────────────────────────────────
  Color get navBgColor     => _isDarkGreen ? const Color(0xFF0A2010) : Colors.white;
  Color get iconUnselColor => _isDarkGreen ? const Color(0xFF4CAF50) : const Color(0xFF9E9E9E);
}
